### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by christinawu2008** [wtsi-hpag/scaffHiC#4]
Hi there,

I'm trying to run scaffhic but keep getting segmentation fault, core dump. Do you have a clue?
I have it successfully installed as it shows the correct message after installation.

Thanks 

Cheers,
Chen

**Comment by christinawu2008** [comment]
sorted.

**Comment by yuzhenpeng** [comment]
Hi, do you solved this problem. @zning01 @christinawu2008
